app:
   name: My app
   description: Welcome to ${app.name}

my:
  greeting: Hello world
  list:
    values: One,Two,Three


db:
  connections : "{connectionString: 'http://_ ', username: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200

management.endpoints.web.exposure.include: "*"
